"""empty message

Revision ID: 541e902c40fd
Revises: 9807b3e0a769
Create Date: 2024-08-23 15:30:01.469417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '541e902c40fd'
down_revision = '9807b3e0a769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameter_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('formula_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('parameter_data_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('parameter_data_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'thermochemistry_data', ['formula_id'], ['id'])
        batch_op.drop_column('original_formula_id')
        batch_op.drop_column('result_formula_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parameter_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_formula_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('original_formula_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('parameter_data_ibfk_2', 'thermochemistry_data', ['result_formula_id'], ['id'])
        batch_op.create_foreign_key('parameter_data_ibfk_1', 'thermochemistry_data', ['original_formula_id'], ['id'])
        batch_op.drop_column('formula_id')

    # ### end Alembic commands ###
