"""empty message

Revision ID: 9807b3e0a769
Revises: 
Create Date: 2024-08-23 15:12:08.572546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9807b3e0a769'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thermochemistry_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('original_formula', sa.String(length=50), nullable=False),
    sa.Column('result_formula', sa.String(length=50), nullable=False),
    sa.Column('data_flag', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('units', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('parameter_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data_found', sa.String(length=50), nullable=False),
    sa.Column('temperature_range', sa.String(length=50), nullable=False),
    sa.Column('A', sa.Float(), nullable=False),
    sa.Column('B', sa.Float(), nullable=False),
    sa.Column('C', sa.Float(), nullable=False),
    sa.Column('D', sa.Float(), nullable=False),
    sa.Column('E', sa.Float(), nullable=False),
    sa.Column('F', sa.Float(), nullable=False),
    sa.Column('G', sa.Float(), nullable=False),
    sa.Column('H', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('original_formula_id', sa.Integer(), nullable=True),
    sa.Column('result_formula_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['original_formula_id'], ['thermochemistry_data.id'], ),
    sa.ForeignKeyConstraint(['result_formula_id'], ['thermochemistry_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parameter_data')
    op.drop_table('user')
    op.drop_table('thermochemistry_data')
    # ### end Alembic commands ###
