"""empty message

Revision ID: b0012c83be92
Revises: d17f3874d65e
Create Date: 2024-08-23 20:57:21.240042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0012c83be92'
down_revision = 'd17f3874d65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_path',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('database_name', sa.String(length=100), nullable=False),
    sa.Column('belonging', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('database_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_name',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('database_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('belonging', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('database_path')
    # ### end Alembic commands ###
