"""empty message

Revision ID: d17f3874d65e
Revises: 541e902c40fd
Create Date: 2024-08-23 19:17:34.130918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17f3874d65e'
down_revision = '541e902c40fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_name',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('database_name', sa.String(length=100), nullable=False),
    sa.Column('belonging', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('database_name')
    # ### end Alembic commands ###
